# -*- coding: utf-8 -*-
"""Multiple Neuron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bbs8WJBGDfXXR8isT_oxJlTeB4jLIgKl
"""

#Muhammad Yuda Pratama/21091397025

#inisialisasi numpy
#Multiple Neuron dengan Neuron 5
import numpy as np

#inisialisasi variabel dengan Input Layer 10
inputs = [1.0, 0.2, 6.3, 3.0, 2.1, 7.0, 4.1, 3.3, 0.9, 1.2]

weights = [[0.2, 3.0, 3.5, 0.3, -2.1, 0.7, 3.7, 2.1, 0.9, -4.0],
           [5.7, 2.6, 4.6, 1.0, -9.0, -3.6, 5.8, 3.9, 4.8, 1.3],
           [4.5, 8.5, -7.2, 4.0, 9.2, 2.3, 4.2, 4.0, 1.9, -5.3],
           [4.0, 5.1, 4.6, 3.5, 2.9, 7.5, 1.8, 9.4, -4.1, 0.66],
           [-8.6, 5.0, 2.0, 5.6, 4.6, -0.45, 7.8, 9.8, 2.7, 4.0]]

#bias ada 5 angka karena Neuronnya 5
biases = [0.8, 6.0, 1.2, 5.0, 3.0]

#output
output = np.dot(weights, inputs) + biases

#print output
print(output)