# -*- coding: utf-8 -*-
"""Single Neuron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bbs8WJBGDfXXR8isT_oxJlTeB4jLIgKl
"""

#Muhammad Yuda Pratama/21091397025

#inisialisasi numpy
#Single Neuron dengan Neuron 1
import numpy as np

#inisialisasi variabel
inputs = [1, 9, 6, 5, 7, 4, 3, 10, 8, 2]
weights = [0.5, 0.2, 0.4, 1.0, 6.0, 0.9, 0.1, 9.0, 0.5, 0.8]
bias = 9

#output
output = np.dot(weights, inputs) + bias

#print output
print(output)